### ISSUE TITLE
Reserveringsscherm - ReservationApp

### ISSUE THREAD

**Issue by Yor0071** [Yor0071/OOSDD-D1#41]
- [x] Maak een schermontwerp om een reservering te plaatsen op basis van de ERD
- [x] Maak een use case beschrijving
- [x] Maak een nieuwe ContentPage genaamd ReservationPage
- [x] Maak velden en date pickers aan om een reservering aan te maken
- [x] Zorg ervoor dat de reservering in de database komt.
- [x] Een popupje tonen dat de reservering gelukt is en je een email ontvangt (email komt in sprint 3) als je op OK drukt ga je naar de plattegrond scherm

**Comment by Derrin616** [comment]
![Image](https://github.com/user-attachments/assets/080d0e9d-714e-4f5f-bf9f-69322deb77ad)
