### ISSUE TITLE
Tabel reserveringen - AdministrationApp

### ISSUE THREAD

**Issue by Yor0071** [Yor0071/OOSDD-D1#43]
- [x] Maak een schermontwerp om alle info uit de database te tonen in een tabel
- [x] Maak een Use case beschrijving voor deze taak
- [x] Maak een nieuwe ContentPage aan genaamd ReservationsTablePage
- [x] Alle gegevens van de database per reservering worden weergeven in de tabel
- [x] De tabel kan worden gefilterd op datum/naam/email/plaats (Enkele zoekbalk die al deze 4 kolommen doorzoekt)

**Comment by Derrin616** [comment]
![Image](https://github.com/user-attachments/assets/8e629edb-5448-4217-a701-42741c473a37)
